services:
  app:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    env_file: ./.env
    networks:
      - my_network
networks:
  my_network: